language: go

go:
  - "1.10.x"
  - "1.11.x"

env:
  global:
    - GO111MODULE=on

script:
  - go build github.com/kocircuit/kocircuit/lang/ko
  - go test ./...
  - ko test 
    github.com/kocircuit/kocircuit/lib
    github.com/kocircuit/kocircuit/lib/encoding/json
    github.com/kocircuit/kocircuit/lib/encoding/yaml
    github.com/kocircuit/kocircuit/lib/file/path
    github.com/kocircuit/kocircuit/lib/net/http
    github.com/kocircuit/kocircuit/lib/set
    github.com/kocircuit/kocircuit/lib/strings
    github.com/kocircuit/kocircuit/lib/sync
    github.com/kocircuit/kocircuit/lib/web/xml
    github.com/kocircuit/kocircuit/lib/web/html
    github.com/kocircuit/kocircuit/lib/web/wiki