language: go

go:
  - "1.10.x"
  - "1.11.x"

env:
  global:
    - GO111MODULE=on

install:
  - go get github.com/golang/protobuf/proto
  - go get github.com/golang/protobuf/protoc-gen-go/descriptor
  - go build github.com/kocircuit/kocircuit/lang/ko

script:
  - go test ./...
  - ./ko test 
    github.com/kocircuit/kocircuit/lib
    github.com/kocircuit/kocircuit/lib/set
    github.com/kocircuit/kocircuit/lib/sync
    github.com/kocircuit/kocircuit/lib/web
