language: go

go:
  - "1.10.x"
  - "1.11.x"

env:
  global:
    - GO111MODULE=on

script:
  - go get github.com/kocircuit/kocircuit/lang/ko
  - go test ./...
  - ko test github.com/kocircuit/kocircuit/lib
