
[[dependencies]]
  branch = "master"
  name = "github.com/fatih/color"

[[dependencies]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[dependencies]]
  branch = "master"
  name = "github.com/olekukonko/tablewriter"

[[dependencies]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[dependencies]]
  branch = "master"
  name = "github.com/spf13/viper"
